### ISSUE TITLE
FYI Lists performance, resetting selectedIndex

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1367]
I have been doing some investigations, this has to do with a previous issue last week as well.

I think there is something seriously wrong with an invalidation sequence on a list and when the parent resizes.

For one each time a parent resizes it is setting the selected index to 0 on lists.

I am writing this right now and will provide a repro hopefully in the next couple days as I try and narrow down exactly what is happening but it is almost locking the UI and fps drops on things that worked fine in feathers 2.x.

Also something weird I have noticed, the less items the list has the less it affects the performance of a resize.

**Comment by joshtynjala** [comment]
> Also something weird I have noticed, the less items the list has the less it affects the performance of a resize.

This usually means that it's creating an item renderer for every item in the data provider. Something may not be strict enough about the measurement.

**Comment by teotigraphix** [comment]
Yes! I noticed it wasn't virtualizing, at least that is what I remember from yesterday.

**Comment by joshtynjala** [comment]
My commit to AnchorLayout may fix your performance issue, if the List was inside an AnchorLayout. However, there may be other things that affect the performance too.

I'm not sure what would cause the selectedIndex to reset to 0. Maybe you're somehow replacing the data provider. That's one way that Feathers will automatically change the selectedIndex. I guess I could possibly imagine a bug in a SpinnerList where its selectedIndex changes on resize. However, I assume you'd specifically mention SpinnerList if that's what you were using.

**Comment by teotigraphix** [comment]
Yeah I'm not using spinnerlist. I am setting aside some time tomorrow to see if I can isolate the problem.

The list I notices yesterday was on a HorizontalLayout witha  ScrollContainer in DrawersApplication.

Something changed, I had to switch component impls for now just to get it to work right. I'm not resetting the dataProivider either. I use MVC so I am updating the dp but the problem happens when I close a left Drawer and the layout expands. It takes around 2 seconds to close with the lists, when I remove the lists and manually layout the exact same item renderers with a manual layout it is instant close.

So, the selectedIndex is getting reset when a drawer is shut, that is where the resize is coming from.

**Comment by joshtynjala** [comment]
> The list I noticed yesterday was in a HorizontalLayout witha ScrollContainer in DrawersApplication.

Was the list in the content part of the Drawers component, or inside one of the drawers?

Is the list a sibling of the ScrollContainer or a child? If it's a sibling, what is the parent?

With those two clarifications, I can investigate too. I actually see a couple of places in Drawers were there may be issues, but they may or may not be related to your issue.

**Comment by teotigraphix** [comment]
The lists (plural) were in the content.

One list was a child of the drawers content

HGroup is just a LayoutGroup. The main parent is a PanelScreen, I have these chopped up in sub components so its hard to get them all in here.
```
    <component:HGroup percentWidth="100" percentHeight="100">
        
        <f:ScrollContainer id="scrollContainer"
                           scrollBarDisplayMode="none"
                           horizontalScrollPolicy="off"
                           verticalScrollPolicy="off">
            
            <f:layoutData>
                <f:HorizontalLayoutData percentWidth="100" percentHeight="100"/>
            </f:layoutData>
            
            <f:layout>
                <f:HorizontalLayout/>
            </f:layout>
            
        </f:ScrollContainer>
        
        <scene:SceneList id="sceneList"
                         scroll="sceneList_scrollHandler(event)">
            
            <scene:layoutData>
                <f:HorizontalLayoutData percentHeight="100"/>
            </scene:layoutData>
            
        </scene:SceneList>
        
    </component:HGroup>
```

**Comment by teotigraphix** [comment]
The above was my older code that I ported two days ago and changed LayoutGroup root to Panel

**Comment by joshtynjala** [comment]
I'm pretty sure I discovered the issue(s) you were running into. Under a number of different circumstances, List/Panel/ScrollContainer and other Scroller subclasses had started invalidating too often when they didn't need to. Mainly due to the new feature where minimum dimensions are calculated when auto-sizing. There needed to be additional checks to see if changing the minimum dimensions of a component actually mattered or not. So, now components will avoid invalidation when it's not needed, and I'm seeing significant performance improvements. There were some places where I was considering it a known issue that certain things had become slower, and that seems to be cleared up now.

I also fixed some issues in Drawers where if a drawer contained a list, it could measure the list without virtualization the first time. That may have contributed to your problem too.

I still haven't seen a list's selectedIndex reset to 0, though.

**Comment by teotigraphix** [comment]
I tired rebuilding feathers to get the latest code using the SDK but kept running into problems, so I gave up.

**Comment by teotigraphix** [comment]
BTW I tried rebuilding the swcs using library projects and point the manifest to the feathers manifest.xml in the current beta sdk. But when things compiled and I tired swapping the swcs starling/feathers out in the sdk'd libs directory I got a bunch of errors saying my components in MXML did not implement IUIComponent.

**Comment by teotigraphix** [comment]
I can also verify that in this code, all the item renderers are being create and the list is not being virtualized. I would love to try the new code but I am at a loss of how to do it using the sdk.

**Comment by joshtynjala** [comment]
Yeah, it's tricky. It needs to be merged into the "mxml" branch so that you get all the [Bindable] metadata and things. Then, you need to build the source code in that branch with the SDK. I'll do the merge today and then you should be able to make something work.

**Comment by joshtynjala** [comment]
Okay, I merged the latest changes into the mxml branch.

**Comment by teotigraphix** [comment]
Ok, bear with me because I am still having problems conceptualizing this build.

So I need to have the SDK repo checked out, the run the base build.xml file?

**Comment by joshtynjala** [comment]
You could do that. You need to make sure that the Git submodules in frameworks/projects/feathers/feathers and frameworks/projects/starling/Starling-Framework are updated properly. Feathers should be the head of the mxml branch, and Starling should be the v2.0.1 tag.

Or you could try to build the source from the mxml branch of BowlerHatLLC/feathers using your existing beta SDK the same way that you tried earlier. I think your main issue was using the master branch, which was missing important parts that are needed to work with MXML.

**Comment by teotigraphix** [comment]
OK option 2 worked for me, so I think I could help you test stuff a lot more now since I am using the SDK and it was impossible for me to test your changes.

How long does it take you to do that tricky merge because I am all set up now recompiling starling and feathers for the sdk.

I need to add back problem components but, since the beta SDK was released, did you majorly change how Drawers slide in and out? With the same code, I am getting extremely different behavior from left and right drawers.

**Comment by joshtynjala** [comment]
> How long does it take you to do that tricky merge because I am all set up now recompiling starling and feathers for the sdk.

Most of the time, the source merges with no problems. I removed a bunch of files in the mxml branch, like the examples and documentation, and I need to tell Git that these files are still removed when they changed in the master branch. Then, I build the SDK and run the SDK tests to be sure that nothing broke. It probably took me ten minutes total this time. This was an easy one.

> did you majorly change how Drawers slide in and out? With the same code, I am getting extremely different behavior from left and right drawers.

I made some minor changes to Drawers. Nothing extreme.

**Comment by teotigraphix** [comment]
OK, well for one without touching anything, a left drawer that slid open OVER the content is no pushing the content right.

So instead of the content being under it, the content is now over it when closing.

With the left drawer open, opening the right drawer when the left is docked, undocks and closes the left. But when the right drawer is closed, the content is minus the width of the left drawer(which is not shown BUT should be open)

Below, the left drawer is docked and I just closed the right drawer.

![capture](https://cloud.githubusercontent.com/assets/226417/15186684/f99492ec-176b-11e6-90e2-639428817525.PNG)

**Comment by joshtynjala** [comment]
Oh, I see the bug. I'll get that fixed. In the meantime, if you use the new RelativeDepth.ABOVE constant instead of the old Drawer.OPEN_MODE_ABOVE, that should probably clear up your issue.

**Comment by teotigraphix** [comment]
What does it mean that I don't have this class RelativeDepth? I pulled the changes from mxml, say your deletes and your edits merged up to the 11th, but I don't have RelativeDepth.

**Comment by joshtynjala** [comment]
I don't know, but it's there:

https://github.com/BowlerHatLLC/feathers/blob/mxml/source/feathers/layout/RelativeDepth.as

**Comment by teotigraphix** [comment]
Ok, something happened. I have that in the source path of the feathers library project but for some reason the swc didn't update right in the SDK swcs.

**Comment by teotigraphix** [comment]
Ok, after 30 minutes I realized maybe I should restart the IDE. :)

Your fix corrects the issue, and I have RelativeDepth after restarting. So the build swc thing works to update the sdk libs.

**Comment by joshtynjala** [comment]
Oh, yeah. The IDE probably loads the SDK SWCs into memory for code suggestions and things.

**Comment by teotigraphix** [comment]
With the new code I have the sshot below. That list on the left is piano keys which has 128 list items and I am using a subclass of LayoutGroupListItemRenderer. I set the dataProvider ONCE and all item renderers are created, I traced in the initialize() method of the renderer.

I know I am not using the List weird, it's just a list with custom item renderers

![capture1](https://cloud.githubusercontent.com/assets/226417/15188698/1cadb44e-1775-11e6-9dd5-6aeb7142b809.PNG)

**Comment by teotigraphix** [comment]
Actually I stand corrected.

My DP has 85 items, before the list is even on screen I get 155 calls to the item renderer.initialize()! Thee is something very weird going on, and the DP is set once.

**Comment by teotigraphix** [comment]
More info. This call stack is from right after the dp has been set. It repeats 85 times exactly the same;

```
caustic.guide.ui.component.pattern.renderers::ScaleListItemRenderer/initialize	
feathers.core::FeathersControl/initializeInternal	
feathers.core::FeathersControl/feathersControl_addedToStageHandler	
starling.events::EventDispatcher/invokeEvent	
starling.events::EventDispatcher/dispatchEvent	
starling.display::DisplayObject/dispatchEvent	
starling.display::DisplayObjectContainer/broadcastEvent	
starling.display::DisplayObjectContainer/broadcastEventWith	
starling.display::DisplayObjectContainer/addChildAt	
starling.display::DisplayObjectContainer/addChild	
feathers.controls.supportClasses::ListDataViewPort/createRenderer	
feathers.controls.supportClasses::ListDataViewPort/refreshLayoutTypicalItem	
feathers.controls.supportClasses::ListDataViewPort/draw	
feathers.core::FeathersControl/validate	
feathers.controls::Scroller/refreshViewPortBoundsForMeasurement	
feathers.controls::Scroller/refreshViewPort	
feathers.controls::Scroller/draw	
feathers.controls::List/draw	
feathers.core::FeathersControl/validate	
feathers.controls::LayoutGroup/validateChildren	
feathers.controls::LayoutGroup/draw	
feathers.core::FeathersControl/validate	
feathers.layout::HorizontalLayout/validateItems	
feathers.layout::HorizontalLayout/layout	
feathers.controls::LayoutGroup/draw	
feathers.core::FeathersControl/validate	
feathers.layout::VerticalLayout/validateItems	
feathers.layout::VerticalLayout/layout	
feathers.controls::LayoutGroup/draw	
feathers.core::FeathersControl/validate	
feathers.layout::VerticalLayout/validateItems	
feathers.layout::VerticalLayout/layout	
feathers.controls::LayoutGroup/draw	
feathers.core::FeathersControl/validate	
feathers.layout::VerticalLayout/validateItems	
feathers.layout::VerticalLayout/layout	
feathers.controls::LayoutGroup/draw	
caustic.ui.dialog::Dialog/draw	
caustic.guide.ui.dialog::PatternSelectionDialog/draw	
feathers.core::FeathersControl/validate	
feathers.core::DefaultPopUpManager/centerPopUp	
feathers.core::DefaultPopUpManager/addPopUp	
feathers.core::PopUpManager$/addPopUp	
caustic.ui.dialog::Dialog$/show	
caustic.guide.ui.dialog::PatternSelectionDialog$/show	
ShowPatternSelectionDialogStep/execute	
```

**Comment by teotigraphix** [comment]
Then... after what seems to be an invalidation, wait frame, this call stack is called what seems to be about 45 more times;

But there is about 3-5 seconds of lag during these to call stacks.

```
caustic.guide.ui.component.pattern.renderers::ScaleListItemRenderer/initialize	
feathers.core::FeathersControl/initializeInternal	
feathers.core::FeathersControl/feathersControl_addedToStageHandler	
starling.events::EventDispatcher/invokeEvent	
starling.events::EventDispatcher/dispatchEvent	
starling.display::DisplayObject/dispatchEvent	
starling.display::DisplayObjectContainer/broadcastEvent	
starling.display::DisplayObjectContainer/broadcastEventWith	
starling.display::DisplayObjectContainer/addChildAt	
starling.display::DisplayObjectContainer/addChild	
feathers.controls.supportClasses::ListDataViewPort/createRenderer	
feathers.controls.supportClasses::ListDataViewPort/renderUnrenderedData	
feathers.controls.supportClasses::ListDataViewPort/refreshRenderers	
feathers.controls.supportClasses::ListDataViewPort/draw	
feathers.core::FeathersControl/validate	
feathers.controls::Scroller/refreshViewPortBoundsForMeasurement	
feathers.controls::Scroller/refreshViewPort	
feathers.controls::Scroller/draw	
feathers.controls::List/draw	
feathers.core::FeathersControl/validate	
feathers.layout::HorizontalLayout/validateItems	
feathers.layout::HorizontalLayout/layout	
feathers.controls::LayoutGroup/draw	
feathers.core::FeathersControl/validate	
feathers.layout::HorizontalLayout/validateItems	
feathers.layout::HorizontalLayout/layout	
feathers.controls::LayoutGroup/draw	
feathers.core::FeathersControl/validate	
feathers.layout::VerticalLayout/validateItems	
feathers.layout::VerticalLayout/layout	
feathers.controls::LayoutGroup/draw	
feathers.core::FeathersControl/validate	
feathers.layout::VerticalLayout/validateItems	
feathers.layout::VerticalLayout/layout	
feathers.controls::LayoutGroup/draw	
feathers.core::FeathersControl/validate	
feathers.layout::VerticalLayout/validateItems	
feathers.layout::VerticalLayout/layout	
feathers.controls::LayoutGroup/draw	
caustic.ui.dialog::Dialog/draw	
caustic.guide.ui.dialog::PatternSelectionDialog/draw	
feathers.core::FeathersControl/validate	
feathers.core::ValidationQueue/advanceTime	
starling.animation::Juggler/advanceTime	
starling.core::Starling/advanceTime	
starling.core::Starling/nextFrame	
starling.core::Starling/onEnterFrame	
```

**Comment by teotigraphix** [comment]
BTW, I am spending all day trying to reduce this down for a repro for you. This is a nasty bug that has to be squashed. It definitely has to do with measurements.

**Comment by joshtynjala** [comment]
Do you use AnchorLayoutData with percentWidth or percentHeight anywhere in that screen?

**Comment by teotigraphix** [comment]
Nope, I got rid of any AnchorLayout stuff for testing since you said that might be an issue, but it didn't change anything, it's all LayoutGroups with either vertical or horizontal layouts.

I am making an empty project right now and trying to recreate my base setup to see if I can reproduce this with the List renderers

**Comment by joshtynjala** [comment]
Damn, I was hoping that would be it. I just fixed an issue where virtualization would break for the initial measurement when using percentWidth and percentHeight on AnchorLayoutData.

**Comment by teotigraphix** [comment]
I got a repro project! I'm emailing you a zip.

Just on startup this creates 387 item renderers.

![capture3](https://cloud.githubusercontent.com/assets/226417/15192121/ddd51102-1785-11e6-9fae-83a7fdd7e447.PNG)

**Comment by teotigraphix** [comment]
I sent you an email with the project zipped up, I am using FB right now.

**Comment by joshtynjala** [comment]
Thanks, I'll take a look!

**Comment by joshtynjala** [comment]
For future reference, here is the layout recreated in pure ActionScript:

	var drawers:Drawers = new Drawers();
	this.addChild(drawers);
	
	var leftList:List = new List();
	leftList.dataProvider = new ListCollection(["One", "Two", "Three"]);
	drawers.leftDrawer = leftList;
	
	var navigator:ScreenNavigator = new ScreenNavigator();

	drawers.content = navigator;
	
	var testPanel1:PanelScreen = new PanelScreen();
	testPanel1.title = "Panel 1";
	testPanel1.layout = new VerticalLayout();

	var pianoRollPane:LayoutGroup = new LayoutGroup();
	pianoRollPane.layout = new HorizontalLayout();
	pianoRollPane.layoutData = new VerticalLayoutData(100, 100);
	testPanel1.addChild(pianoRollPane);
	
	var scaleList:List = new List();
	scaleList.layoutData = new HorizontalLayoutData(NaN, 100);
	pianoRollPane.addChild(scaleList);
	
	var scrollContainer:ScrollContainer = new ScrollContainer();
	scrollContainer.layoutData = new HorizontalLayoutData(100, 100);
	pianoRollPane.addChild(scrollContainer);

	var result:Array = [];
	for (var i:int = 0; i < 200; i++)
	{
		result[i] = {label:i.toString()};
	}
	scaleList.dataProvider = new ListCollection(result);
	
	var bottomList:List = new List();
	bottomList.layout = new HorizontalLayout();
	bottomList.layoutData = new VerticalLayoutData(100);
	testPanel1.addChild(bottomList);

	navigator.addScreen("one", new ScreenNavigatorItem(testPanel1));

	navigator.showScreen("one");

**Comment by joshtynjala** [comment]
The following simplified version can reproduce the broken layout virtualization:

	var testPanel1:PanelScreen = new PanelScreen();
	testPanel1.autoSizeMode = AutoSizeMode.STAGE;
	testPanel1.title = "Panel 1";
	testPanel1.layout = new VerticalLayout();
	this.addChild(testPanel1);

	var scaleList:List = new List();
	scaleList.layoutData = new VerticalLayoutData(NaN, 100);
	testPanel1.addChild(scaleList);

	var result:Array = [];
	for (var i:int = 0; i < 200; i++)
	{
		result[i] = {label:i.toString()};
	}
	scaleList.dataProvider = new ListCollection(result);

**Comment by teotigraphix** [comment]
So were these notes to yourself? I have such complicated apps it was hard to boil it down to what you just showed :)

**Comment by joshtynjala** [comment]
Yes, in case I need to recreate the same testing environment in the future.

**Comment by joshtynjala** [comment]
The latest commits should fix it. I merged them into the mxml branch.

**Comment by teotigraphix** [comment]
Hmm... Now my app won't start, I am getting this with the same exact code I was running 5 minutes ago;

```
Main Thread (Suspended: ArgumentError: maxVisibleHeight cannot be NaN)	
	feathers.controls.supportClasses::LayoutViewPort/set maxVisibleHeight	
	feathers.controls::Scroller/refreshViewPortBoundsForMeasurement	
	feathers.controls::Scroller/refreshViewPort	
	feathers.controls::Scroller/draw	
	feathers.controls::ScrollContainer/draw	
	feathers.controls::Panel/draw	
	caustic.app.ui.drawers::NavigationDrawer/draw	
	feathers.core::FeathersControl/validate	
	feathers.controls::Drawers/layoutChildren	
	feathers.controls::Drawers/draw	
	feathers.core::FeathersControl/validate	
	feathers.core::ValidationQueue/advanceTime	
	feathers.controls.supportClasses::BaseScreenNavigator/showScreenInternal	
	feathers.controls::ScreenNavigator/showScreen	
	caustic.app.controller.core::AbstractScreenLauncher/setScreen	
	caustic.app.controller.core::AbstractApplicationController/context_selectedAccessChangedHandler	
	org.robotlegs.starling.base::EventMap/routeEventToListener	
	Function/<anonymous>	
	starling.events::EventDispatcher/invokeEvent	
	starling.events::EventDispatcher/dispatchEvent	
	starling.events::EventDispatcher/dispatchEventWith	
	org.robotlegs.starling.mvcs::Actor/dispatchWith	
	caustic.app.model.core::AbstractModel/dispatchWith	
	caustic.app.ui::AbstractUIState/set selectedNavigationItem	
	caustic.app.ui::AbstractUIState/setSelectedNavigationItem	
	caustic.guide.controller::ApplicationController/launchInitialScreen	
	caustic.app.controller.core::AbstractApplicationController/configureDrawers	
	caustic.app.controller.core::AbstractApplicationController/context_applicationCompleteHandler	
	caustic.guide.controller::ApplicationController/context_applicationCompleteHandler	
	org.robotlegs.starling.base::EventMap/routeEventToListener	
	Function/<anonymous>	
	starling.events::EventDispatcher/invokeEvent	
	starling.events::EventDispatcher/dispatchEvent	
	starling.events::EventDispatcher/dispatchEventWith	
	org.robotlegs.starling.mvcs::Command/dispatchWith	
	caustic.app.configuration.command::AbstractStartupCcommand/delayedComplete	
	Function/http://adobe.com/AS3/2006/builtin::apply [no source]	
	starling.animation::DelayedCall/advanceTime	
	starling.animation::Juggler/advanceTime	
	starling.core::Starling/advanceTime	
	starling.core::Starling/nextFrame	
	starling.core::Starling/onEnterFrame	
```

**Comment by joshtynjala** [comment]
I'm guessing that _topViewPortOffset or _bottomViewPortOffset is probably NaN in refreshViewPortBoundsForMeasurement(). Can you verify that in your debugger for me?

**Comment by teotigraphix** [comment]
My NavigationDrawer is a Panel subclass and that goes in the left drawer, here are the variables in the refresh method;

this	NavigationDrawer (@f70b851)	
horizontalWidthOffset	16 [0x10]	
verticalHeightOffset	Infinity	
measureBackground	null	
viewPortMinWidth	0	
viewPortMinHeight	-Infinity	
oldIgnoreViewPortResizing	false	
backgroundMinWidth	16 [0x10]	
backgroundMinHeight	600 [0x258]	


_bottomViewPortOffset is 48 and _topViewPortOffset  is Inifinity

**Comment by teotigraphix** [comment]
On thing to note is that I am putting Panels inside this Panel But I took those out and it's still doing it.

I tried a bare Panel and it worked, so I am backtracking and trying to see what the hell I am doing that is screwing this up in the Panel styling or something.

**Comment by joshtynjala** [comment]
Okay, I stopped infinity values from propagating where they shouldn't. Try the latest commits in the mxml branch!

**Comment by teotigraphix** [comment]
I found what was doing it.

I have a custom header and footer render. It was the footer, I have a ButtonGroup with percent width/height set to 100.

Once I took out the ButtonGroup the app ran.

**Comment by teotigraphix** [comment]
HAHA This days has just sucked! Now I am getting the below with everything enabled again.

```
Main Thread (Suspended: ArgumentError: maxWidth cannot be NaN)	
	feathers.core::FeathersControl/set maxWidth	
	feathers.layout::HorizontalLayout/validateItems	
	feathers.layout::HorizontalLayout/layout	
	feathers.controls::LayoutGroup/draw	
	caustic.app.ui.drawers.navigation::NavigationDrawerFooter/draw	
	feathers.core::FeathersControl/validate	
	feathers.controls::Panel/calculateViewPortOffsets	
	feathers.controls::Scroller/refreshViewPort	
	feathers.controls::Scroller/draw	
	feathers.controls::ScrollContainer/draw	
	feathers.controls::Panel/draw	
	caustic.app.ui.drawers::NavigationDrawer/draw	
	feathers.core::FeathersControl/validate	
	feathers.controls::Drawers/layoutChildren	
	feathers.controls::Drawers/draw	
	feathers.core::FeathersControl/validate	
	feathers.core::ValidationQueue/advanceTime	
	feathers.controls.supportClasses::BaseScreenNavigator/showScreenInternal	
	feathers.controls::ScreenNavigator/showScreen	
	caustic.app.controller.core::AbstractScreenLauncher/setScreen	
	caustic.app.controller.core::AbstractApplicationController/context_selectedAccessChangedHandler	
	org.robotlegs.starling.base::EventMap/routeEventToListener	
	Function/<anonymous>	
	starling.events::EventDispatcher/invokeEvent	
	starling.events::EventDispatcher/dispatchEvent	
	starling.events::EventDispatcher/dispatchEventWith	
	org.robotlegs.starling.mvcs::Actor/dispatchWith	
	caustic.app.model.core::AbstractModel/dispatchWith	
	caustic.app.ui::AbstractUIState/set selectedNavigationItem	
	caustic.app.ui::AbstractUIState/setSelectedNavigationItem	
	caustic.guide.controller::ApplicationController/launchInitialScreen	
	caustic.app.controller.core::AbstractApplicationController/configureDrawers	
	caustic.app.controller.core::AbstractApplicationController/context_applicationCompleteHandler	
	caustic.guide.controller::ApplicationController/context_applicationCompleteHandler	
	org.robotlegs.starling.base::EventMap/routeEventToListener	
	Function/<anonymous>	
	starling.events::EventDispatcher/invokeEvent	
	starling.events::EventDispatcher/dispatchEvent	
	starling.events::EventDispatcher/dispatchEventWith	
	org.robotlegs.starling.mvcs::Command/dispatchWith	
	caustic.app.configuration.command::AbstractStartupCcommand/delayedComplete	
	Function/http://adobe.com/AS3/2006/builtin::apply [no source]	
	starling.animation::DelayedCall/advanceTime	
	starling.animation::Juggler/advanceTime	
	starling.core::Starling/advanceTime	
	starling.core::Starling/nextFrame	
	starling.core::Starling/onEnterFrame	
```

**Comment by joshtynjala** [comment]
Yeah, I see where that could happen. Fix incoming soon.

**Comment by teotigraphix** [comment]
Yeah I took out the ButtonBar for the nav and I get this; :)

![capture34](https://cloud.githubusercontent.com/assets/226417/15199306/29ae7c6a-17ab-11e6-89da-396312c4613e.PNG)

**Comment by teotigraphix** [comment]
What is weird to is when I updated to the mxml branch the first time today my header where it says Navigation shrunk like that, before it was the same height as the main content's header. I must have some styling wrong or something.

**Comment by joshtynjala** [comment]
> I must have some styling wrong or something.

There was a bug in 3.0.0-beta where the Header height was calculated wrong, so that's why they used to be equal. You need to give the header on the left a minHeight that accounts for the size of the items in the header on the right to make them match up.

**Comment by teotigraphix** [comment]
Ok, great, on a positive note! Your fix for the virtualization kicked ass! I got the patterns Panel work and it is totally virtualized again and the drawer opens and shuts correctly and fast!

![asdasdasd](https://cloud.githubusercontent.com/assets/226417/15199462/4d67f3ba-17ac-11e6-99bd-93d5ac03764a.PNG)

**Comment by joshtynjala** [comment]
Well, give it another try! If that doesn't work, I'll take a break for the night, and start fresh tomorrow.

**Comment by teotigraphix** [comment]
Yeah, I 'm in NH so I am just turning off the computer so I will try it 2 am your time. :)

**Comment by teotigraphix** [comment]
Good to go! Everything works as expected right now, great job Josh, thanks for the time! If I find anything else, I will start a new issue.

**Comment by joshtynjala** [comment]
Great! Thanks, Mike.
