### ISSUE TITLE
Button setFontStylesForState doesn't work properly

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1572]
Hello.

I want to use setFontStylesForState method of the Button class to set different label color for each Button state. I use this code:

```
var upFormat:starling.text.TextFormat = new starling.text.TextFormat(
		GlobalTheme.MyriadPro_BoldCondIt, 30, 0x000000);

var hoverFormat:starling.text.TextFormat = new starling.text.TextFormat(
		GlobalTheme.MyriadPro_BoldCondIt, 30, 0xA5CDCD);

var downFormat:starling.text.TextFormat = new starling.text.TextFormat(
		GlobalTheme.MyriadPro_BoldCondIt, 30, 0x90B4B4);

button.setFontStylesForState(ButtonState.UP, upFormat);
button.setFontStylesForState(ButtonState.OVER, hoverFormat);
button.setFontStylesForState(ButtonState.DOWN, downFormat);
```
But it doesn't work properly. On hover state, label doesn't change color from UP to HOVER. After clicking on the button, label color doesn't change to UP from DOWN.But it doesn't work as it should. On hover state label doesn't change color. After clicking on the button label color doesn't change to UP.

**Comment by joshtynjala** [comment]
Which text renderer are you using? I recently discovered a bug with TextFieldTextRenderer where it would not change font styles properly. It has been fixed on Github.

**Comment by subdan** [comment]
I use TextFieldTextRenderer. I updated feathers sources and it still doesn't work properly.

`button.setFontStylesForState(ButtonState.OVER, hoverFormat);` doesn't work.

**Comment by joshtynjala** [comment]
It looks like you're using the wrong ButtonState class. In Feathers, it's ButtonState.HOVER.

**Comment by subdan** [comment]
Oops. I've used starling ButtonState class. Sorry.
