### ISSUE TITLE
Buggy Alert with TopcoatLightMobileTheme

### ISSUE THREAD

**Issue by CrazyFlasher** [BowlerHatLLC/feathers#1683]
Alert layout seems to be broken in `TopcoatLightMobileTheme`.
Fine with `MetalWorksMobileTheme`
Feathers 3.3.1

See screens:
http://joxi.ru/nAyzdViX0555rZ - broken
http://joxi.ru/Dr8Kx8CkaEE5A6 - ok

**Comment by joshtynjala** [comment]
Already fixed in the latest source here on GitHub. 😄

**Comment by CrazyFlasher** [comment]
Took 3.4.1 release and issue is still there:
![image](https://user-images.githubusercontent.com/1607138/36635583-7a613972-19c0-11e8-8057-1efd7e9c8848.png)

**Comment by joshtynjala** [comment]
I did not include the fix in 3.4.1. It will be included in 3.5.

**Comment by CrazyFlasher** [comment]
ok, cool

**Comment by CrazyFlasher** [comment]
Was it fix in theme, feathers or just in assets fla?
I need to know what component to rebuild

**Comment by joshtynjala** [comment]
It was fixed in the theme.

**Comment by CrazyFlasher** [comment]
in theme code or just assets design fixes?

**Comment by joshtynjala** [comment]
I know for sure that I changed the assets a bit, but I don't recall if I changed the code too.

**Comment by joshtynjala** [comment]
Commit eb941d7ebcdeccddbdc166882a79cb2067abadf3

I made a change to the code, but it doesn't appear to be required for the fix to alert.

**Comment by CrazyFlasher** [comment]
is it possible to download topcoat_light_mobile.fla somewhere before release 3.5?

**Comment by joshtynjala** [comment]
[topcoat_light_mobile.zip](https://github.com/BowlerHatLLC/feathers/files/1760384/topcoat_light_mobile.zip)

**Comment by CrazyFlasher** [comment]
thank you very much!
